
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    restart: always
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    ports:
      - 9092:9092
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1

  rest:
    build:
      context: ./rest
    image: rest-service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    links:
      - kafka:kafka

  calculator:
    build:
      context: ./calculator
    image: calculator-service
    depends_on:
      - kafka
    links:
      - kafka:kafka
